const content = document.getElementById("content");
const contactTitle = document.createElement("h1");
const contact1 = document.createElement("div");
const c1Name = document.createElement("h3");
const c1Occupation = document.createElement("p");
const c1Phone = document.createElement("p");
const c1Email = document.createElement("p");
const c1Image = document.createElement("img");
const contact2 = document.createElement("div");
const c2Name = document.createElement("h3");
const c2Occupation = document.createElement("p");
const c2Phone = document.createElement("p");
const c2Email = document.createElement("p");
const c2Image = document.createElement("img");
const contact3 = document.createElement("div");
const c3Name = document.createElement("h3");
const c3Occupation = document.createElement("p");
const c3Phone = document.createElement("p");
const c3Email = document.createElement("p");
const c3Image = document.createElement("img");

contactTitle.textContent = "Contact";
c1Name.textContent = "Gandalf";
c1Occupation.textContent = "Cashier";
c1Phone.textContent = "666-676-6666";
c1Email.textContent = "Gdalf@fake.com";
c1Image.src = "images/wizard.jpg";
c1Image.alt = "Gandalf";
c2Name.textContent = "Artorias";
c2Occupation.textContent = "Manager";
c2Phone.textContent = "676-666-6666";
c2Email.textContent = "art@fake.com";
c2Image.src = "images/knight.jpg";
c2Image.alt = "Artorias";
c3Name.textContent = "Alonne";
c3Occupation.textContent = "Customer Service Representative";
c3Phone.textContent = "666-666-6766";
c3Email.textContent = "Alonne@fake.com";
c1Image.src = "images/samurai.jpg";
c1Image.alt = "Alonne";

contact1.appendChild(c1Name);
contact1.appendChild(c1Occupation);
contact1.appendChild(c1Phone);
contact1.appendChild(c1Email);
contact2.appendChild(c2Name);
contact2.appendChild(c2Occupation);
contact2.appendChild(c2Phone);
contact2.appendChild(c2Email);
contact3.appendChild(c3Name);
contact3.appendChild(c3Occupation);
contact3.appendChild(c3Phone);
contact3.appendChild(c3Email);
content.appendChild(contactTitle);
content.appendChild(contact1);
content.appendChild(contact2);
content.appendChild(contact2);
