import knight from "./images/knight.jpg";
import samurai from "./images/samurai.jpg";
import wizard from "./images/wizard.jpg";
import wand from "./images/wand.png";

export function contact() {
  const content = document.getElementById("content");
  const cTitleOuter = document.createElement("div");
  const cTitleInner = document.createElement("div");
  const contactTitle = document.createElement("h1");
  const decoration1 = document.createElement("img");
  const decoration2 = document.createElement("img");
  const contact1Outer = document.createElement("div");
  const contact1Inner = document.createElement("div");
  const c1Name = document.createElement("h3");
  const c1Occupation = document.createElement("p");
  const c1Phone = document.createElement("p");
  const c1Email = document.createElement("p");
  const c1Image = document.createElement("img");
  const contact2Outer = document.createElement("div");
  const contact2Inner = document.createElement("div");
  const c2Name = document.createElement("h3");
  const c2Occupation = document.createElement("p");
  const c2Phone = document.createElement("p");
  const c2Email = document.createElement("p");
  const c2Image = document.createElement("img");
  const contact3Outer = document.createElement("div");
  const contact3Inner = document.createElement("div");
  const c3Name = document.createElement("h3");
  const c3Occupation = document.createElement("p");
  const c3Phone = document.createElement("p");
  const c3Email = document.createElement("p");
  const c3Image = document.createElement("img");

  contactTitle.textContent = "Contact";
  decoration1.src = wand;
  decoration1.alt = "Wand";
  decoration2.src = wand;
  decoration2.alt = "Wand";
  c1Name.textContent = "Gandalf";
  c1Occupation.textContent = "Cashier";
  c1Phone.textContent = "666-676-6666";
  c1Email.textContent = "Gdalf@fake.com";
  c1Image.src = wizard;
  c1Image.alt = "Gandalf";
  c2Name.textContent = "Artorias";
  c2Occupation.textContent = "Manager";
  c2Phone.textContent = "676-666-6666";
  c2Email.textContent = "art@fake.com";
  c2Image.src = knight;
  c2Image.alt = "Artorias";
  c3Name.textContent = "Alonne";
  c3Occupation.textContent = "Customer Service Representative";
  c3Phone.textContent = "666-666-6766";
  c3Email.textContent = "Alonne@fake.com";
  c3Image.src = samurai;
  c3Image.alt = "Alonne";

  decoration1.classList.add("d1");
  decoration2.classList.add("d2");
  c1Image.classList.add("contactImg");
  c2Image.classList.add("contactImg");
  c3Image.classList.add("contactImg");
  cTitleOuter.classList.add("outer");
  cTitleInner.classList.add("inner");
  cTitleInner.classList.add("header");
  contact1Outer.classList.add("outer");
  contact1Inner.classList.add("inner");
  contact2Outer.classList.add("outer");
  contact2Inner.classList.add("inner");
  contact3Outer.classList.add("outer");
  contact3Inner.classList.add("inner");

  cTitleInner.appendChild(decoration1);
  cTitleInner.appendChild(contactTitle);
  cTitleInner.appendChild(decoration2);
  cTitleOuter.appendChild(cTitleInner);
  contact1Inner.appendChild(c1Name);
  contact1Inner.appendChild(c1Occupation);
  contact1Inner.appendChild(c1Phone);
  contact1Inner.appendChild(c1Email);
  contact1Inner.appendChild(c1Image);
  contact1Outer.appendChild(contact1Inner);
  contact2Inner.appendChild(c2Name);
  contact2Inner.appendChild(c2Occupation);
  contact2Inner.appendChild(c2Phone);
  contact2Inner.appendChild(c2Email);
  contact2Inner.appendChild(c2Image);
  contact2Outer.appendChild(contact2Inner);
  contact3Inner.appendChild(c3Name);
  contact3Inner.appendChild(c3Occupation);
  contact3Inner.appendChild(c3Phone);
  contact3Inner.appendChild(c3Email);
  contact3Inner.appendChild(c3Image);
  contact3Outer.appendChild(contact3Inner);
  content.appendChild(cTitleOuter);
  content.appendChild(contact1Outer);
  content.appendChild(contact2Outer);
  content.appendChild(contact3Outer);
}
