import biscuit from "./images/biscuit.jpg";
import bowl from "./images/bowl.jpg";
import bread from "./images/bread.jpg";
import cape from "./images/cape.jpg";
import chicken from "./images/chicken.jpg";
import croissant from "./images/croissant.jpg";
import goblet from "./images/goblet.jpg";
import oats from "./images/oats.jpg";
import pancakes from "./images/pancakes.jpg";
import platter from "./images/platter.jpg";
import skillet from "./images/skillet.jpg";
import souffle from "./images/souffle.jpg";
import potion from "./images/potion.png";

export function menu() {
  const content = document.getElementById("content");
  const mTitleOuter = document.createElement("div");
  const mTitleInner = document.createElement("div");
  const menuTitle = document.createElement("h1");
  const decoration1 = document.createElement("img");
  const decoration2 = document.createElement("img");
  const beverages = document.createElement("div");
  const bTitleOuter = document.createElement("div");
  const bTitleInner = document.createElement("div");
  const beverageTitle = document.createElement("h2");
  const b1Outer = document.createElement("div");
  const b1Inner = document.createElement("div");
  const b1Name = document.createElement("h3");
  const b1Descrip = document.createElement("p");
  const b1Price = document.createElement("p");
  const b1Image = document.createElement("img");
  const b2Outer = document.createElement("div");
  const b2Inner = document.createElement("div");
  const b2Name = document.createElement("h3");
  const b2Descrip = document.createElement("p");
  const b2Price = document.createElement("p");
  const b2Image = document.createElement("img");

  const sides = document.createElement("div");
  const sTitleOuter = document.createElement("div");
  const sTitleInner = document.createElement("div");
  const sideTitle = document.createElement("h2");
  const s1Outer = document.createElement("div");
  const s1Inner = document.createElement("div");
  const s1Name = document.createElement("h3");
  const s1Descrip = document.createElement("p");
  const s1Price = document.createElement("p");
  const s1Image = document.createElement("img");
  const s2Outer = document.createElement("div");
  const s2Inner = document.createElement("div");
  const s2Name = document.createElement("h3");
  const s2Descrip = document.createElement("p");
  const s2Price = document.createElement("p");
  const s2Image = document.createElement("img");

  const entrées = document.createElement("div");
  const eTitleOuter = document.createElement("div");
  const eTitleInner = document.createElement("div");
  const entréeTitle = document.createElement("h2");
  const e1Outer = document.createElement("div");
  const e1Inner = document.createElement("div");
  const e1Name = document.createElement("h3");
  const e1Descrip = document.createElement("p");
  const e1Price = document.createElement("p");
  const e1Image = document.createElement("img");
  const e2Outer = document.createElement("div");
  const e2Inner = document.createElement("div");
  const e2Name = document.createElement("h3");
  const e2Descrip = document.createElement("p");
  const e2Price = document.createElement("p");
  const e2Image = document.createElement("img");
  const e3Outer = document.createElement("div");
  const e3Inner = document.createElement("div");
  const e3Name = document.createElement("h3");
  const e3Descrip = document.createElement("p");
  const e3Price = document.createElement("p");
  const e3Image = document.createElement("img");
  const e4Outer = document.createElement("div");
  const e4Inner = document.createElement("div");
  const e4Name = document.createElement("h3");
  const e4Descrip = document.createElement("p");
  const e4Price = document.createElement("p");
  const e4Image = document.createElement("img");
  const e5Outer = document.createElement("div");
  const e5Inner = document.createElement("div");
  const e5Name = document.createElement("h3");
  const e5Descrip = document.createElement("p");
  const e5Price = document.createElement("p");
  const e5Image = document.createElement("img");
  const e6Outer = document.createElement("div");
  const e6Inner = document.createElement("div");
  const e6Name = document.createElement("h3");
  const e6Descrip = document.createElement("p");
  const e6Price = document.createElement("p");
  const e6Image = document.createElement("img");
  const e7Outer = document.createElement("div");
  const e7Inner = document.createElement("div");
  const e7Name = document.createElement("h3");
  const e7Descrip = document.createElement("p");
  const e7Price = document.createElement("p");
  const e7Image = document.createElement("img");
  const e8Outer = document.createElement("div");
  const e8Inner = document.createElement("div");
  const e8Name = document.createElement("h3");
  const e8Descrip = document.createElement("p");
  const e8Price = document.createElement("p");
  const e8Image = document.createElement("img");

  menuTitle.textContent = "Menu";
  beverageTitle.textContent = "Beverages";
  sideTitle.textContent = "Sides";
  entréeTitle.textContent = "Entrées";
  decoration1.src = potion;
  decoration1.alt = "potion";
  decoration2.src = potion;
  decoration2.alt = "Potion";
  b1Name.textContent = "Potion Madness";
  b1Descrip.textContent =
    "A delectable, warm drink said to be made by wizards. It is said that one sip pf this potion will bring a smile to your face.";
  b1Price.textContent = "$3.99";
  b1Image.src = cape;
  b1Image.alt = "Potion Madness";
  b2Name.textContent = "Goblins' Goblet";
  b2Descrip.textContent =
    "A small goblet filled with a refreshing, fruity drink that is usually a delicacy among goblins.";
  b2Price.textContent = "$4.29";
  b2Image.src = goblet;
  b2Image.alt = "Goblins' Goblet";
  s1Name.textContent = "Peasant Bread";
  s1Descrip.textContent =
    "Bread that is made by peasants, but so delicious that is considered food for the gods.";
  s1Price.textContent = "$1.99";
  s1Image.src = bread;
  s1Image.alt = "Peasant Bread";
  s2Name.textContent = "Priviledged Oats";
  s2Descrip.textContent =
    "Oats typically eaten by nobles, but through a little magic is now available to all!";
  s2Price.textContent = "$1.99";
  s2Image.src = oats;
  s2Image.alt = "Privileged Oats";
  e1Name.textContent = "Elfen Croissant";
  e1Descrip.textContent =
    "Two sweet, warm croissant filled with cream cheese and top with powdered sugar. Served with a drink of your choice.";
  e1Price.textContent = "$8.99";
  e1Image.src = croissant;
  e1Image.alt = "Elfen Croissant";
  e2Name.textContent = "Orcs' Platter";
  e2Descrip.textContent =
    "Eggs, 3 sausage, 3 slices of bacon, and 3 pancakes. This dish is common breakfast for orcs.";
  e2Price.textContent = "$13.99";
  e2Image.src = platter;
  e2Image.alt = "Orcs' Platter";
  e3Name.textContent = "Demon Scorchin Skillet";
  e3Descrip.textContent =
    "Eggs, spinach, scorching demon sauce, and mushrooms all in one sizzling hot skillet! *Ingredients can be added for additional charge. Please talk to your server";
  e3Price.textContent = "$12.99";
  e3Image.src = skillet;
  e3Image.alt = "Demon Scorchin Skillet";
  e4Name.textContent = "Roasted Falcon Sandwhich";
  e4Descrip.textContent =
    "Fried chicken, with lettuce, pickles, and cheese. Comes with a side of fries.";
  e4Price.textContent = "$11.99";
  e4Image.src = chicken;
  e4Image.alt = "Roasted Falcon Sandwhich";
  e5Name.textContent = "Knights' Breakfast Bowl";
  e5Descrip.textContent =
    "Strawberrries, blueberries, oats, yogurt, and chia seeds all come together to make a delicious, fresh breakfast. Knights eat this bowl to replenish their strength.";
  e5Price.textContent = "$10.99";
  e5Image.src = bowl;
  e5Image.alt = "Knights' Breakfast Bowl";
  e6Name.textContent = "Clerics Biscuits And Gravy";
  e6Descrip.textContent =
    "A stack of freshly made biscuit that comes with side of our signature gravy and bacon.";
  e6Price.textContent = "$8.99";
  e6Image.src = biscuit;
  e6Image.alt = "Clerics Biscuits and Gravy";
  e7Name.textContent = "Thiefs' Pancakes";
  e7Descrip.textContent =
    "Unlimited pancakes with creamy buttery and sweet syrup. These pancakes are so good you'll want to steal them!";
  e7Price.textContent = "$8.99";
  e7Image.src = pancakes;
  e7Image.alt = "Thiefs' Pancakes";
  e8Name.textContent = "Maiden Soufflé";
  e8Descrip.textContent =
    "A simple, elegant soufflé that is made by only the kindest of maidens. Served with a side of your choice.";
  e8Price.textContent = "$7.99";
  e8Image.src = souffle;
  e8Image.alt = "Maiden Soufflé";

  decoration1.classList.add("d1");
  decoration2.classList.add("d2");
  b1Name.classList.add("nItem");
  b2Name.classList.add("nItem");
  s1Name.classList.add("nItem");
  s2Name.classList.add("nItem");
  e1Name.classList.add("nItem");
  e2Name.classList.add("nItem");
  e3Name.classList.add("nItem");
  e4Name.classList.add("nItem");
  e5Name.classList.add("nItem");
  e6Name.classList.add("nItem");
  e7Name.classList.add("nItem");
  e8Name.classList.add("nItem");

  b1Descrip.classList.add("dItem");
  b2Descrip.classList.add("dItem");
  s1Descrip.classList.add("dItem");
  s2Descrip.classList.add("dItem");
  e1Descrip.classList.add("dItem");
  e2Descrip.classList.add("dItem");
  e3Descrip.classList.add("dItem");
  e4Descrip.classList.add("dItem");
  e5Descrip.classList.add("dItem");
  e6Descrip.classList.add("dItem");
  e7Descrip.classList.add("dItem");
  e8Descrip.classList.add("dItem");

  b1Price.classList.add("pItem");
  b2Price.classList.add("pItem");
  s1Price.classList.add("pItem");
  s2Price.classList.add("pItem");
  e1Price.classList.add("pItem");
  e2Price.classList.add("pItem");
  e3Price.classList.add("pItem");
  e4Price.classList.add("pItem");
  e5Price.classList.add("pItem");
  e6Price.classList.add("pItem");
  e7Price.classList.add("pItem");
  e8Price.classList.add("pItem");

  b1Image.classList.add("menuImg");
  b2Image.classList.add("menuImg");
  s1Image.classList.add("menuImg");
  s2Image.classList.add("menuImg");
  e1Image.classList.add("menuImg");
  e2Image.classList.add("menuImg");
  e3Image.classList.add("menuImg");
  e4Image.classList.add("menuImg");
  e5Image.classList.add("menuImg");
  e6Image.classList.add("menuImg");
  e7Image.classList.add("menuImg");
  e8Image.classList.add("menuImg");

  mTitleOuter.classList.add("outer");
  bTitleOuter.classList.add("outer");
  sTitleOuter.classList.add("outer");
  eTitleOuter.classList.add("outer");
  b1Outer.classList.add("outer");
  b2Outer.classList.add("outer");
  s1Outer.classList.add("outer");
  s2Outer.classList.add("outer");
  e1Outer.classList.add("outer");
  e2Outer.classList.add("outer");
  e3Outer.classList.add("outer");
  e4Outer.classList.add("outer");
  e5Outer.classList.add("outer");
  e6Outer.classList.add("outer");
  e7Outer.classList.add("outer");
  e8Outer.classList.add("outer");
  mTitleInner.classList.add("inner");
  mTitleInner.classList.add("header");
  bTitleInner.classList.add("inner");
  sTitleInner.classList.add("inner");
  eTitleInner.classList.add("inner");
  b1Inner.classList.add("inner");
  b2Inner.classList.add("inner");
  s1Inner.classList.add("inner");
  s2Inner.classList.add("inner");
  e1Inner.classList.add("inner");
  e2Inner.classList.add("inner");
  e3Inner.classList.add("inner");
  e4Inner.classList.add("inner");
  e5Inner.classList.add("inner");
  e6Inner.classList.add("inner");
  e7Inner.classList.add("inner");
  e8Inner.classList.add("inner");
  beverages.classList.add("menuContainer");
  sides.classList.add("menuContainer");
  entrées.classList.add("menuContainer");

  mTitleInner.appendChild(decoration1);
  mTitleInner.appendChild(menuTitle);
  mTitleInner.appendChild(decoration2);
  mTitleOuter.appendChild(mTitleInner);
  bTitleInner.appendChild(beverageTitle);
  bTitleOuter.appendChild(bTitleInner);
  b1Inner.appendChild(b1Name);
  b1Inner.appendChild(b1Descrip);
  b1Inner.appendChild(b1Price);
  b1Inner.appendChild(b1Image);
  b1Outer.appendChild(b1Inner);
  b2Inner.appendChild(b2Name);
  b2Inner.appendChild(b2Descrip);
  b2Inner.appendChild(b2Price);
  b2Inner.appendChild(b2Image);
  b2Outer.appendChild(b2Inner);
  beverages.appendChild(bTitleOuter);
  beverages.appendChild(b1Outer);
  beverages.appendChild(b2Outer);

  sTitleInner.appendChild(sideTitle);
  sTitleOuter.appendChild(sTitleInner);
  s1Inner.appendChild(s1Name);
  s1Inner.appendChild(s1Descrip);
  s1Inner.appendChild(s1Price);
  s1Inner.appendChild(s1Image);
  s1Outer.appendChild(s1Inner);
  s2Inner.appendChild(s2Name);
  s2Inner.appendChild(s2Descrip);
  s2Inner.appendChild(s2Price);
  s2Inner.appendChild(s2Image);
  s2Outer.appendChild(s2Inner);
  sides.appendChild(sTitleOuter);
  sides.appendChild(s1Outer);
  sides.appendChild(s2Outer);

  eTitleInner.appendChild(entréeTitle);
  eTitleOuter.appendChild(eTitleInner);
  e1Inner.appendChild(e1Name);
  e1Inner.appendChild(e1Descrip);
  e1Inner.appendChild(e1Price);
  e1Inner.appendChild(e1Image);
  e1Outer.appendChild(e1Inner);
  e2Inner.appendChild(e2Name);
  e2Inner.appendChild(e2Descrip);
  e2Inner.appendChild(e2Price);
  e2Inner.appendChild(e2Image);
  e2Outer.appendChild(e2Inner);
  e3Inner.appendChild(e3Name);
  e3Inner.appendChild(e3Descrip);
  e3Inner.appendChild(e3Price);
  e3Inner.appendChild(e3Image);
  e3Outer.appendChild(e3Inner);
  e4Inner.appendChild(e4Name);
  e4Inner.appendChild(e4Descrip);
  e4Inner.appendChild(e4Price);
  e4Inner.appendChild(e4Image);
  e4Outer.appendChild(e4Inner);
  e5Inner.appendChild(e5Name);
  e5Inner.appendChild(e5Descrip);
  e5Inner.appendChild(e5Price);
  e5Inner.appendChild(e5Image);
  e5Outer.appendChild(e5Inner);
  e6Inner.appendChild(e6Name);
  e6Inner.appendChild(e6Descrip);
  e6Inner.appendChild(e6Price);
  e6Inner.appendChild(e6Image);
  e6Outer.appendChild(e6Inner);
  e7Inner.appendChild(e7Name);
  e7Inner.appendChild(e7Descrip);
  e7Inner.appendChild(e7Price);
  e7Inner.appendChild(e7Image);
  e7Outer.appendChild(e7Inner);
  e8Inner.appendChild(e8Name);
  e8Inner.appendChild(e8Descrip);
  e8Inner.appendChild(e8Price);
  e8Inner.appendChild(e8Image);
  e8Outer.appendChild(e8Inner);

  entrées.appendChild(eTitleOuter);
  entrées.appendChild(e1Outer);
  entrées.appendChild(e2Outer);
  entrées.appendChild(e3Outer);
  entrées.appendChild(e4Outer);
  entrées.appendChild(e5Outer);
  entrées.appendChild(e6Outer);
  entrées.appendChild(e7Outer);
  entrées.appendChild(e8Outer);

  content.appendChild(mTitleOuter);
  content.appendChild(beverages);
  content.appendChild(sides);
  content.appendChild(entrées);
}
//Continue changing element names to outer and inner for titles
