const menuTitle = document.createElement("div");
const beverages = document.createElement("div");
const beverageTitle = document.createElement("h2");
const beverage1 = document.createElement("div");
const beverage2 = document.createElement("div");
const sides = document.createElement("div");
const sideTitle = document.createElement("h2");
const side1 = document.createElement("div");
const side2 = document.createElement("div");
const entrées = document.createElement("div");
const entréeTitle = document.createElement("h2");
const entrée1 = document.createElement("div");
const entrée2 = document.createElement("div");
const entrée3 = document.createElement("div");
const entrée4 = document.createElement("div");
const entrée5 = document.createElement("div");
const entrée6 = document.createElement("div");
const entrée7 = document.createElement("div");
const entrée8 = document.createElement("div");

beverages.appendChild(beverageTitle);
sides.appendChild(beverage1);
sides.appendChild(beverage2);
sides.appendChild(sideTitle);
sides.appendChild(side1);
sides.appendChild(side2);
entrées.appendChild(entréeTitle);
entrées.appendChild(entrée1);
entrées.appendChild(entrée2);
entrées.appendChild(entrée3);
entrées.appendChild(entrée4);
entrées.appendChild(entrée5);
entrées.appendChild(entrée6);
entrées.appendChild(entrée7);
entrées.appendChild(entrée8);
content.appendChild(menuTitle);
content.appendChild(beverages);
content.appendChild(sides);
content.appendChild(entrées);
